/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import bean.MmsProduto;
import dao.MmsProdutoDAO;
import tools.Util;

/**
 *
 * @author halom
 */
public class MmsTelaProdutoIA extends javax.swing.JDialog {

    /**
     * Creates new form MmsTelaProdutoIA
     */
    public MmsTelaProdutoIA(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Inclusão e Alteração de Produtos");
        setLocationRelativeTo(null);
        
    }
    
    
    public MmsProduto viewBean() {
         MmsProduto produto = new MmsProduto();
        produto.setMmsIdproduto(Util.strInt(jTxtMMSCodigoP.getText()));
        produto.setMmsNome(jTxtMMSNomeP.getText());
        produto.setMmsDescricao(jTxtMMSDescricao.getText());
        produto.setMmsPreco(Util.strDouble(jTxtMMSPreco.getText()));
        produto.setMmsConsumo((jTxtMMSconsumo.getText()));
        produto.setMmsMemoria(jTxtMMSMemoria.getText());
        produto.setMmsDimensao(jTxtMMSDimensao.getText());
        produto.setMmsPeso(Util.strInt(jTxtMMSPeso.getText()));
        produto.setMmsMarca(jTxtMMSMarca.getText());
        produto.setMmsGarantia(jTxtMMSGarantia.getText());
        produto.setMmsModelo(jTxtMMSModelo.getText());
        
        return produto;
     }
    
     public void beanView(MmsProduto mmsProduto){
    jTxtMMSCodigoP.setText(Util.intStr(mmsProduto.getMmsIdproduto()));
    jTxtMMSNomeP.setText(mmsProduto.getMmsNome());
    jTxtMMSDescricao.setText(mmsProduto.getMmsDescricao());
    jTxtMMSDimensao.setText(mmsProduto.getMmsDimensao());
    jTxtMMSGarantia.setText(mmsProduto.getMmsGarantia());
    jTxtMMSMarca.setText(mmsProduto.getMmsMarca());
    jTxtMMSMemoria.setText(mmsProduto.getMmsMemoria());
    jTxtMMSModelo.setText(mmsProduto.getMmsModelo());
    jTxtMMSPeso.setText(Util.intStr(mmsProduto.getMmsPeso()));
    jTxtMMSPreco.setText(Util.doubleStr(mmsProduto.getMmsPreco()));
    jTxtMMSconsumo.setText(mmsProduto.getMmsConsumo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtMMSCodigoP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtMMSNomeP = new javax.swing.JTextField();
        jTxtMMSDescricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtMMSPreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtMMSconsumo = new javax.swing.JTextField();
        jTxtMMSMemoria = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTxtMMSDimensao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtMMSPeso = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtMMSMarca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxtMMSGarantia = new javax.swing.JTextField();
        jTxtMMSModelo = new javax.swing.JTextField();
        jBtnMMSConfirmar = new javax.swing.JButton();
        jBtnMMSCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código Produto");

        jLabel2.setText("Nome Produto");

        jLabel3.setText("Descrição");

        jLabel4.setText("Preço");

        jTxtMMSPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMMSPrecoActionPerformed(evt);
            }
        });

        jLabel5.setText("Consumo");

        jTxtMMSMemoria.setText("Memória");

        jLabel7.setText("Dimensão");

        jLabel8.setText("Peso");

        jLabel9.setText("Marca");

        jLabel6.setText("Garantia");

        jLabel10.setText("Modelo");

        jBtnMMSConfirmar.setText("Confirmar");
        jBtnMMSConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMMSConfirmarActionPerformed(evt);
            }
        });

        jBtnMMSCancelar.setText("Cancelar");
        jBtnMMSCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMMSCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtMMSDescricao)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTxtMMSCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTxtMMSNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTxtMMSPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTxtMMSconsumo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnMMSConfirmar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTxtMMSMemoria)
                                .addComponent(jTextField1)
                                .addComponent(jLabel8)
                                .addComponent(jTxtMMSPeso)
                                .addComponent(jLabel6)
                                .addComponent(jTxtMMSGarantia, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtMMSDimensao)
                            .addComponent(jTxtMMSMarca)
                            .addComponent(jTxtMMSModelo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jBtnMMSCancelar))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMMSCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMMSNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtMMSDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtMMSconsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMMSPreco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtMMSMemoria)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMMSDimensao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMMSPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMMSMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMMSGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtMMSModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnMMSConfirmar)
                    .addComponent(jBtnMMSCancelar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtMMSPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMMSPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMMSPrecoActionPerformed

    private void jBtnMMSCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMMSCancelarActionPerformed
        setVisible(false);
        Util.limparCampos(jTxtMMSCodigoP,jTxtMMSDescricao, jTxtMMSDimensao, jTxtMMSGarantia, jTxtMMSMarca, jTxtMMSMemoria, jTxtMMSModelo, jTxtMMSNomeP, jTxtMMSPeso,jTxtMMSconsumo);
    }//GEN-LAST:event_jBtnMMSCancelarActionPerformed

    private void jBtnMMSConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMMSConfirmarActionPerformed

    MmsProduto mmsProduto = viewBean();
    MmsProdutoDAO mmsProdutoDAO = new MmsProdutoDAO();
    mmsProdutoDAO.insert(mmsProduto);        
    
         Util.limparCampos(jTxtMMSCodigoP,jTxtMMSDescricao, jTxtMMSDimensao, jTxtMMSGarantia, jTxtMMSMarca, jTxtMMSMemoria, jTxtMMSModelo, jTxtMMSNomeP, jTxtMMSPeso,jTxtMMSconsumo);  
    }//GEN-LAST:event_jBtnMMSConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MmsTelaProdutoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MmsTelaProdutoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MmsTelaProdutoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MmsTelaProdutoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MmsTelaProdutoIA dialog = new MmsTelaProdutoIA(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnMMSCancelar;
    private javax.swing.JButton jBtnMMSConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTxtMMSCodigoP;
    private javax.swing.JTextField jTxtMMSDescricao;
    private javax.swing.JTextField jTxtMMSDimensao;
    private javax.swing.JTextField jTxtMMSGarantia;
    private javax.swing.JTextField jTxtMMSMarca;
    private javax.swing.JLabel jTxtMMSMemoria;
    private javax.swing.JTextField jTxtMMSModelo;
    private javax.swing.JTextField jTxtMMSNomeP;
    private javax.swing.JTextField jTxtMMSPeso;
    private javax.swing.JTextField jTxtMMSPreco;
    private javax.swing.JTextField jTxtMMSconsumo;
    // End of variables declaration//GEN-END:variables
}
