/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import bean.MmsCategoria;
import dao.MmsCategoriaDAO;
import tools.Util;
import views.MmsTelaCategoria;

/**
 *
 * @author halom
 */
public class MmsTelaCategoriaIA extends javax.swing.JDialog {
 
        boolean incluir;
        MmsTelaCategoria mmsTelaCategoria;
    /**
     * Creates new form MmsTelaCategoriaIA
     */
    public MmsTelaCategoriaIA(java.awt.Frame parent, boolean modal) {
         super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
    }

 public MmsTelaCategoriaIA(boolean incluindo) {
    // Faça algo com a variável booleana recebida, se necessário.
    this.incluir = incluindo;
    initComponents();
}



    
    
    public MmsCategoria viewBean(){
         MmsCategoria categoria = new MmsCategoria();
        categoria.setMmsIdcategoria(Util.strInt(jTxtMMSCodigo.getText()));
        categoria.setMmsNome(jTxtMMSNome.getText());
        categoria.setMmsDescricao(jTxtMMSDescricao.getText());
        categoria.setMmsTipoPlaca(jTxtMMSTipoPlaca.getText());
        categoria.setMmsConsumoMinimo(Util.strInt(jTxtMmsConsumomin.getText()));
        categoria.setMmsConsumoMaximo(Util.strInt(jTxtMmsconsumoMax.getText()));
        categoria.setMmsTempMedia(jTxtMmsTempMédia.getText());
        if(jChbMmsSliCrossfire.isSelected()==true){
        categoria.setMmsSliCrossFire("S");
        }else{
        categoria.setMmsSliCrossFire("N");
        }    
        return categoria;
    }
    
    public void beanView(MmsCategoria mmsCategoria){
    jTxtMMSCodigo.setText(Util.intStr(mmsCategoria.getMmsIdcategoria()));
    jTxtMMSDescricao.setText(mmsCategoria.getMmsDescricao());
    jTxtMMSNome.setText(mmsCategoria.getMmsNome());
    jTxtMMSTipoPlaca.setText(mmsCategoria.getMmsTipoPlaca());
    jTxtMmsConsumomin.setText(Util.intStr(mmsCategoria.getMmsConsumoMinimo()));
    jTxtMmsconsumoMax.setText(Util.intStr(mmsCategoria.getMmsConsumoMaximo()));
    jTxtMmsTempMédia.setText(mmsCategoria.getMmsTempMedia());
     if ( mmsCategoria.getMmsSliCrossFire().equals("S") == true){
           jChbMmsSliCrossfire.setSelected(true);
        } else {
        jChbMmsSliCrossfire.setSelected(false);    
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtMMSCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtMMSNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtMMSDescricao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtMMSTipoPlaca = new javax.swing.JTextField();
        jBtnMMSConfirmar = new javax.swing.JButton();
        jBtnMMSCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTxtMmsConsumomin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtMmsconsumoMax = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtMmsTempMédia = new javax.swing.JTextField();
        jChbMmsSliCrossfire = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel1.setText("Categoria");

        jLabel2.setText("Código de Categoria");

        jLabel3.setText("Nome");

        jLabel4.setText("Descrição");

        jLabel5.setText("Tipo de Placa");

        jBtnMMSConfirmar.setText("Confirmar");
        jBtnMMSConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMMSConfirmarActionPerformed(evt);
            }
        });

        jBtnMMSCancelar.setText("Cancelar");
        jBtnMMSCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMMSCancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("Consumo Min.");

        jLabel7.setText("Consumo Max.");

        jTxtMmsconsumoMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMmsconsumoMaxActionPerformed(evt);
            }
        });

        jLabel8.setText("SLI // CrossFire");

        jLabel9.setText("Temperatura Média");

        jChbMmsSliCrossfire.setText("Ativo?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnMMSConfirmar)
                                .addGap(51, 51, 51)
                                .addComponent(jBtnMMSCancelar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtMMSDescricao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTxtMMSNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(jTxtMMSCodigo, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTxtMMSTipoPlaca, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jTxtMmsConsumomin, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jTxtMmsconsumoMax, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtMmsTempMédia, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jChbMmsSliCrossfire, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(99, 202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtMMSCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtMMSNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtMMSDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtMMSTipoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxtMmsConsumomin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtMmsconsumoMax, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtMmsTempMédia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChbMmsSliCrossfire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnMMSConfirmar)
                    .addComponent(jBtnMMSCancelar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnMMSCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMMSCancelarActionPerformed
       setVisible(false);
        Util.limparCampos(jTxtMMSCodigo, jTxtMMSDescricao, jTxtMMSNome, jTxtMMSTipoPlaca, jTxtMmsConsumomin, jTxtMmsconsumoMax, jTxtMmsTempMédia, jChbMmsSliCrossfire);
    }//GEN-LAST:event_jBtnMMSCancelarActionPerformed

    private void jBtnMMSConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMMSConfirmarActionPerformed
        
        MmsCategoria mmsCategoria = viewBean();
        MmsCategoriaDAO mmsCategoriaDAO = new MmsCategoriaDAO();
        mmsCategoriaDAO.insert(mmsCategoria);
        
        
        Util.limparCampos(jTxtMMSCodigo, jTxtMMSDescricao, jTxtMMSNome, jTxtMMSTipoPlaca, jTxtMmsConsumomin, jTxtMmsconsumoMax, jTxtMmsTempMédia, jChbMmsSliCrossfire);
    }//GEN-LAST:event_jBtnMMSConfirmarActionPerformed

    private void jTxtMmsconsumoMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMmsconsumoMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMmsconsumoMaxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MmsTelaCategoriaIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MmsTelaCategoriaIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MmsTelaCategoriaIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MmsTelaCategoriaIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MmsTelaCategoriaIA dialog = new MmsTelaCategoriaIA(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnMMSCancelar;
    private javax.swing.JButton jBtnMMSConfirmar;
    private javax.swing.JCheckBox jChbMmsSliCrossfire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtMMSCodigo;
    private javax.swing.JTextField jTxtMMSDescricao;
    private javax.swing.JTextField jTxtMMSNome;
    private javax.swing.JTextField jTxtMMSTipoPlaca;
    private javax.swing.JTextField jTxtMmsConsumomin;
    private javax.swing.JTextField jTxtMmsTempMédia;
    private javax.swing.JTextField jTxtMmsconsumoMax;
    // End of variables declaration//GEN-END:variables
}
