/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import bean.MmsCliente;
import bean.MmsVendas;
import bean.MmsVendasProduto;
import dao.MmsClienteDAO;
import dao.MmsProdutoDAO;
import dao.MmsVendasDAO;
import dao.MmsVendasProdutoDAO;


import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;
import tools.VendaControle;
import tools.VendasProdutoControle;


/**
 *
 * @author u07875284120
 */
public class MmsTelaVendas extends javax.swing.JDialog {

     MaskFormatter mascaraData;

    private boolean incluindo;
    MmsVendasDAO mmsVendasDAO;
    MmsVendas mmsvendas;
    VendaControle vendaControle;
    MmsVendasProduto mmsVendasProduto;
    MmsVendasProdutoDAO mmsVendasProdutoDAO;
    VendasProdutoControle vendasProdutoControle;
    MmsCliente mmsCliente;
    MmsTelaVendasPesquisar mmsTelaVendasPesquisar;
    MmsTelaVendasProduto mmsTelaVendasProduto;
    
    
    /**
     * Creates new form MmsVendas
     */
    public MmsTelaVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Tela de Vendas");
        Util.habilitar(false, jTxtNumPedido, jFmtDataVenda, jCboMmsCliente, jCboVendedor, jTxtTotal, jBtnAlterar2, jBtnExcluir2,jBtnIncluir2, jBtnConfirmar, jBtnCancelar );
        setLocationRelativeTo(null);
        mmsVendasDAO = new MmsVendasDAO();
       
       
       
       
        
        MmsClienteDAO mmsclienteDAO = new MmsClienteDAO();
        List listaCli = mmsclienteDAO.listAll(); 
        for (int i = 0; i < listaCli.size(); i++) {
        jCboMmsCliente.addItem((MmsCliente) listaCli.get(i));
        }
        
         vendasProdutoControle = new VendasProdutoControle();
         List lista = new ArrayList();
        vendasProdutoControle.setList(lista);
        jTblseila.setModel(vendasProdutoControle);
        try {
            mascaraData = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(MmsTelaVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFmtDataVenda.setFormatterFactory(new DefaultFormatterFactory(mascaraData));

    }


     public MmsVendas viewBean() {
       MmsVendas mmsVendas = new MmsVendas();
       int id = Util.strInt(jTxtNumPedido.getText());
       mmsVendas.setMmsIdVendas(id);
         try {
             mmsVendas.setMmsDataVenda(Util.strDate(jFmtDataVenda.getText()));
         } catch (ParseException ex) {
             Logger.getLogger(MmsTelaVendas.class.getName()).log(Level.SEVERE, null, ex);
         }
       mmsVendas.setMmsCliente((MmsCliente) jCboMmsCliente.getSelectedItem());
       mmsVendas.setMmsVendedores((int) jCboVendedor.getSelectedIndex());
       double total = Util.strDouble(jTxtTotal.getText());
       mmsVendas.setMmsValor(total);
        return mmsVendas;
    }
     

    public void beanView(MmsVendas vendas) {
        mmsvendas = vendas;
        jTxtNumPedido.setText(String.valueOf(vendas.getMmsIdVendas()));
        jFmtDataVenda.setText(Util.dateStr(vendas.getMmsDataVenda()));
        jCboMmsCliente.setSelectedItem(vendas.getMmsCliente());
        jCboVendedor.setSelectedItem(vendas.getMmsVendedores());
        jTxtTotal.setText(String.valueOf(vendas.getMmsValor()));

       mmsVendasProdutoDAO = new MmsVendasProdutoDAO();
       List listaProd = (List) mmsVendasProdutoDAO.listProduto(mmsvendas);
       vendasProdutoControle.setList(listaProd);
    }

    
    public int getSelectedRowProd() {
        return jTblseila.getSelectedRow();
    
    }
       
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtNumPedido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFmtDataVenda = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCboVendedor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTxtTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblseila = new javax.swing.JTable();
        jBtnIncluir2 = new javax.swing.JButton();
        jBtnAlterar2 = new javax.swing.JButton();
        jBtnExcluir2 = new javax.swing.JButton();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jCboMmsCliente = new javax.swing.JComboBox<MmsCliente>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Num. Pedido");

        jTxtNumPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNumPedidoActionPerformed(evt);
            }
        });

        jLabel2.setText("Data");

        jLabel3.setText("Cliente");

        jLabel4.setText("Vendedor");

        jCboVendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "João Cesar", "Irineu Junior", "Jonathan Iggor", "Nathalia Silva" }));
        jCboVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboVendedorActionPerformed(evt);
            }
        });

        jLabel5.setText("Total");

        jTblseila.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblseila);

        jBtnIncluir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/04 - incluir.png"))); // NOI18N
        jBtnIncluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir2ActionPerformed(evt);
            }
        });

        jBtnAlterar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/01 - alterar.png"))); // NOI18N
        jBtnAlterar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar2ActionPerformed(evt);
            }
        });

        jBtnExcluir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/02 - excluir.png"))); // NOI18N
        jBtnExcluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir2ActionPerformed(evt);
            }
        });

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/04 - incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/01 - alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/02 - excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/05 - ok.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/06 - pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jTxtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jFmtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jCboMmsCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jCboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnExcluir2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnIncluir2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnAlterar2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnIncluir)
                        .addGap(41, 41, 41)
                        .addComponent(jBtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnConfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnPesquisar)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboMmsCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jBtnIncluir2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnAlterar2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnExcluir2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPesquisar))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNumPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNumPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNumPedidoActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        Util.limparCampos(jTblseila, jTxtNumPedido, jTxtTotal, jFmtDataVenda, jCboMmsCliente, jCboVendedor);
        
        MmsTelaVendasPesquisar mmsTelaVendasPesquisar = new MmsTelaVendasPesquisar(null, true);
        mmsTelaVendasPesquisar.setTelaAnterior(this);
        mmsTelaVendasPesquisar.setVisible(true);
        
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        Util.habilitar(true, jTxtNumPedido, jFmtDataVenda, jCboMmsCliente, jCboVendedor, jTxtTotal, jBtnAlterar2, jBtnExcluir2,jBtnIncluir2, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(false, jBtnExcluir, jBtnAlterar, jBtnIncluir, jBtnPesquisar);

      
        vendasProdutoControle.setList(new ArrayList());
        jTxtNumPedido.grabFocus();
        incluindo = true;
        mmsvendas = new MmsVendas();
         Util.limparCampos(jTxtNumPedido, jFmtDataVenda, jCboMmsCliente, jCboVendedor, jTxtTotal);
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        
  Util.habilitar(false, jBtnExcluir, jBtnIncluir, jBtnAlterar, jBtnPesquisar);

        if (mmsvendas != null) {
            
           mmsVendasDAO = new MmsVendasDAO();
                MmsVendasProduto mmsVendasProduto;
                for (int linha = 0; linha < jTblseila.getRowCount(); linha++) {
                    mmsVendasProduto = vendasProdutoControle.getBean(linha);
                    mmsVendasDAO.delete(mmsVendasProduto);}
                
                
            Util.habilitar(true, jTxtNumPedido, jFmtDataVenda, jCboMmsCliente, jCboVendedor, jTxtTotal, jBtnAlterar2, jBtnExcluir2,jBtnIncluir2, jBtnConfirmar, jBtnCancelar);
            Util.habilitar(false, jBtnExcluir, jBtnAlterar, jBtnIncluir, jBtnPesquisar);

        } else {
            Util.mensagem("Deve ser realizada uma pesquisa antes");
        }
        incluindo = false;
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
            
        if (mmsvendas != null) {
            if (Util.perguntar("Deseja excluir o pedido ?") == true) {
                MmsVendasProduto mmsVendasProduto;
                for (int linha = 0; linha < jTblseila.getRowCount(); linha++) {
                    mmsVendasProduto = vendasProdutoControle.getBean(linha);
                    mmsVendasProdutoDAO.delete(mmsVendasProduto);
                }
                mmsVendasDAO.delete(mmsvendas);
            }
        } else {
            Util.mensagem("Deve ser realizada uma pesquisa antes");
        }
        vendasProdutoControle.setList(new ArrayList());
        Util.limparCampos(jTxtNumPedido, jFmtDataVenda, jCboMmsCliente, jCboVendedor, jTxtTotal);
        mmsvendas = null;
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed

         mmsvendas = viewBean();
        if (incluindo == true) {
            mmsVendasDAO.insert(mmsvendas);
             mmsVendasProdutoDAO = new MmsVendasProdutoDAO();
            
            for (int linha = 0; linha < jTblseila.getRowCount(); linha++) {
                mmsVendasProduto = vendasProdutoControle.getBean(linha);
                mmsVendasProduto.setMmsVenda(mmsvendas);
                  mmsVendasProdutoDAO.insert(mmsVendasProduto);
            }
        } else {
            mmsVendasDAO.update(mmsvendas);
            //remover todos os pedidos produtos deste pedido
            mmsVendasProdutoDAO = new MmsVendasProdutoDAO();
            
        
            for (int linha = 0; linha < jTblseila.getRowCount(); linha++) {
                mmsVendasProduto = vendasProdutoControle.getBean(linha);
                mmsVendasProduto.setMmsVenda(mmsvendas);
                mmsVendasProdutoDAO.insert(mmsVendasProduto);
               
            }
            
           
        }
        //habilitar(false);
        Util.limparCampos(jTxtNumPedido, jFmtDataVenda, jCboMmsCliente, jCboVendedor, jTxtTotal);
        vendasProdutoControle.setList(new ArrayList());

        mmsvendas = null;
        
        Util.habilitar(false, jTxtNumPedido, jFmtDataVenda, jCboMmsCliente, jCboVendedor, jTxtTotal, jBtnAlterar2, jBtnExcluir2,jBtnIncluir2, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(true, jBtnExcluir, jBtnAlterar, jBtnIncluir, jBtnPesquisar);
        
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed

       // habilitar(false);
        Util.limparCampos(jTxtNumPedido, jFmtDataVenda, jCboMmsCliente, jCboVendedor, jTxtTotal);
        vendasProdutoControle.setList(new ArrayList());
        mmsvendas = null;
         Util.habilitar(false, jTxtNumPedido, jFmtDataVenda, jCboMmsCliente, jCboVendedor, jTxtTotal, jBtnAlterar2, jBtnExcluir2,jBtnIncluir2, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(true, jBtnExcluir, jBtnAlterar, jBtnIncluir, jBtnPesquisar);
        
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnIncluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir2ActionPerformed
        mmsTelaVendasProduto = new MmsTelaVendasProduto(null, true);
        mmsTelaVendasProduto.setTitle("inclusão de produtos");
        mmsTelaVendasProduto.setTelaAnterior(this);
        mmsTelaVendasProduto.setVisible(true);
    }//GEN-LAST:event_jBtnIncluir2ActionPerformed

    private void jBtnAlterar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar2ActionPerformed
        mmsTelaVendasProduto = new MmsTelaVendasProduto(null, true);
        mmsTelaVendasProduto.setTitle("Alteração de produtos");
        mmsTelaVendasProduto.setTelaAnterior(this);
        
        int linSel = jTblseila.getSelectedRow();
        mmsVendasProduto = (MmsVendasProduto) vendasProdutoControle.getBean(linSel);
        mmsTelaVendasProduto.beanView(mmsVendasProduto);
        mmsTelaVendasProduto.setVisible(true);
        

    }//GEN-LAST:event_jBtnAlterar2ActionPerformed

    private void jBtnExcluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir2ActionPerformed
       int linha = jTblseila.getSelectedRow();
        if (linha == -1) {
            Util.mensagem("Nenhuma linha selecionada");
        } else {
            if (Util.perguntar("Confirma exclusão do produto?") == true) {
                vendasProdutoControle.removeBean(linha);
            }
        }
    }//GEN-LAST:event_jBtnExcluir2ActionPerformed

    private void jCboVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MmsVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MmsVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MmsVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MmsVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MmsTelaVendas dialog = new MmsTelaVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnAlterar2;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnExcluir2;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnIncluir2;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<MmsCliente> jCboMmsCliente;
    private javax.swing.JComboBox<String> jCboVendedor;
    private javax.swing.JFormattedTextField jFmtDataVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblseila;
    private javax.swing.JTextField jTxtNumPedido;
    private javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables

    
}
