package bean;
// Generated 13/09/2023 14:13:26 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MmsCliente generated by hbm2java
 */
@Entity
@Table(name="mms_cliente"
    ,catalog="db_mathias_fleitas"
)
public class MmsCliente  implements java.io.Serializable {


     private int mmsIdcliente;
     private String mmsNome;
     private String mmsCpf;
     private String mmsRg;
     private Date mmsDataNasc;
     private String mmsEmail;
     private String mmsCep;
     private String mmsEndereco;
     private String mmsCidade;
     private int mmsNumeroCasa;
     private String mmsNacionalidade;
     private String mmsCelular;
     private String mmsTelefoneResidencial;
     private int mmsEstadoCivil;
     private int sexo;

    public MmsCliente() {
    }

	
    public MmsCliente(int mmsIdcliente, String mmsNome, String mmsCpf, String mmsRg, String mmsEmail, String mmsCep, String mmsEndereco, String mmsCidade, int mmsNumeroCasa, String mmsNacionalidade, String mmsCelular, String mmsTelefoneResidencial, int mmsEstadoCivil, int sexo) {
        this.mmsIdcliente = mmsIdcliente;
        this.mmsNome = mmsNome;
        this.mmsCpf = mmsCpf;
        this.mmsRg = mmsRg;
        this.mmsEmail = mmsEmail;
        this.mmsCep = mmsCep;
        this.mmsEndereco = mmsEndereco;
        this.mmsCidade = mmsCidade;
        this.mmsNumeroCasa = mmsNumeroCasa;
        this.mmsNacionalidade = mmsNacionalidade;
        this.mmsCelular = mmsCelular;
        this.mmsTelefoneResidencial = mmsTelefoneResidencial;
        this.mmsEstadoCivil = mmsEstadoCivil;
        this.sexo = sexo;
    }
    public MmsCliente(int mmsIdcliente, String mmsNome, String mmsCpf, String mmsRg, Date mmsDataNasc, String mmsEmail, String mmsCep, String mmsEndereco, String mmsCidade, int mmsNumeroCasa, String mmsNacionalidade, String mmsCelular, String mmsTelefoneResidencial, int mmsEstadoCivil, int sexo) {
       this.mmsIdcliente = mmsIdcliente;
       this.mmsNome = mmsNome;
       this.mmsCpf = mmsCpf;
       this.mmsRg = mmsRg;
       this.mmsDataNasc = mmsDataNasc;
       this.mmsEmail = mmsEmail;
       this.mmsCep = mmsCep;
       this.mmsEndereco = mmsEndereco;
       this.mmsCidade = mmsCidade;
       this.mmsNumeroCasa = mmsNumeroCasa;
       this.mmsNacionalidade = mmsNacionalidade;
       this.mmsCelular = mmsCelular;
       this.mmsTelefoneResidencial = mmsTelefoneResidencial;
       this.mmsEstadoCivil = mmsEstadoCivil;
       this.sexo = sexo;
    }
   
     @Id 

    
    @Column(name="mms_idcliente", unique=true, nullable=false)
    public int getMmsIdcliente() {
        return this.mmsIdcliente;
    }
    
    public void setMmsIdcliente(int mmsIdcliente) {
        this.mmsIdcliente = mmsIdcliente;
    }

    
    @Column(name="mms_nome", nullable=false, length=45)
    public String getMmsNome() {
        return this.mmsNome;
    }
    
    public void setMmsNome(String mmsNome) {
        this.mmsNome = mmsNome;
    }

    
    @Column(name="mms_cpf", nullable=false, length=45)
    public String getMmsCpf() {
        return this.mmsCpf;
    }
    
    public void setMmsCpf(String mmsCpf) {
        this.mmsCpf = mmsCpf;
    }

    
    @Column(name="mms_rg", nullable=false, length=45)
    public String getMmsRg() {
        return this.mmsRg;
    }
    
    public void setMmsRg(String mmsRg) {
        this.mmsRg = mmsRg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mms_dataNasc", length=10)
    public Date getMmsDataNasc() {
        return this.mmsDataNasc;
    }
    
    public void setMmsDataNasc(Date mmsDataNasc) {
        this.mmsDataNasc = mmsDataNasc;
    }

    
    @Column(name="mms_email", nullable=false, length=45)
    public String getMmsEmail() {
        return this.mmsEmail;
    }
    
    public void setMmsEmail(String mmsEmail) {
        this.mmsEmail = mmsEmail;
    }

    
    @Column(name="mms_cep", nullable=false, length=45)
    public String getMmsCep() {
        return this.mmsCep;
    }
    
    public void setMmsCep(String mmsCep) {
        this.mmsCep = mmsCep;
    }

    
    @Column(name="mms_endereco", nullable=false, length=90)
    public String getMmsEndereco() {
        return this.mmsEndereco;
    }
    
    public void setMmsEndereco(String mmsEndereco) {
        this.mmsEndereco = mmsEndereco;
    }

    
    @Column(name="mms_cidade", nullable=false, length=80)
    public String getMmsCidade() {
        return this.mmsCidade;
    }
    
    public void setMmsCidade(String mmsCidade) {
        this.mmsCidade = mmsCidade;
    }

    
    @Column(name="mms_numeroCasa", nullable=false)
    public int getMmsNumeroCasa() {
        return this.mmsNumeroCasa;
    }
    
    public void setMmsNumeroCasa(int mmsNumeroCasa) {
        this.mmsNumeroCasa = mmsNumeroCasa;
    }

    
    @Column(name="mms_nacionalidade", nullable=false, length=45)
    public String getMmsNacionalidade() {
        return this.mmsNacionalidade;
    }
    
    public void setMmsNacionalidade(String mmsNacionalidade) {
        this.mmsNacionalidade = mmsNacionalidade;
    }

    
    @Column(name="mms_celular", nullable=false, length=45)
    public String getMmsCelular() {
        return this.mmsCelular;
    }
    
    public void setMmsCelular(String mmsCelular) {
        this.mmsCelular = mmsCelular;
    }

    
    @Column(name="mms_telefoneResidencial", nullable=false, length=45)
    public String getMmsTelefoneResidencial() {
        return this.mmsTelefoneResidencial;
    }
    
    public void setMmsTelefoneResidencial(String mmsTelefoneResidencial) {
        this.mmsTelefoneResidencial = mmsTelefoneResidencial;
    }

    
    @Column(name="mms_estadoCivil", nullable=false)
    public int getMmsEstadoCivil() {
        return this.mmsEstadoCivil;
    }
    
    public void setMmsEstadoCivil(int mmsEstadoCivil) {
        this.mmsEstadoCivil = mmsEstadoCivil;
    }

    
    @Column(name="sexo", nullable=false)
    public int getSexo() {
        return this.sexo;
    }
    
    public void setSexo(int sexo) {
        this.sexo = sexo;
    }




}


