package bean;
// Generated 22/09/2023 15:20:10 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MmsCategoria generated by hbm2java
 */
@Entity
@Table(name="mms_categoria"
    ,catalog="db_mathias_fleitas"
)
public class MmsCategoria  implements java.io.Serializable {


     private int mmsIdcategoria;
     private String mmsNome;
     private String mmsDescricao;
     private String mmsTipoPlaca;

    public MmsCategoria() {
    }

    public MmsCategoria(int mmsIdcategoria, String mmsNome, String mmsDescricao, String mmsTipoPlaca) {
       this.mmsIdcategoria = mmsIdcategoria;
       this.mmsNome = mmsNome;
       this.mmsDescricao = mmsDescricao;
       this.mmsTipoPlaca = mmsTipoPlaca;
    }
   
     @Id 

    
    @Column(name="mms_idcategoria", unique=true, nullable=false)
    public int getMmsIdcategoria() {
        return this.mmsIdcategoria;
    }
    
    public void setMmsIdcategoria(int mmsIdcategoria) {
        this.mmsIdcategoria = mmsIdcategoria;
    }

    
    @Column(name="mms_nome", nullable=false, length=45)
    public String getMmsNome() {
        return this.mmsNome;
    }
    
    public void setMmsNome(String mmsNome) {
        this.mmsNome = mmsNome;
    }

    
    @Column(name="mms_descricao", nullable=false, length=45)
    public String getMmsDescricao() {
        return this.mmsDescricao;
    }
    
    public void setMmsDescricao(String mmsDescricao) {
        this.mmsDescricao = mmsDescricao;
    }

    
    @Column(name="mms_tipoPlaca", nullable=false, length=45)
    public String getMmsTipoPlaca() {
        return this.mmsTipoPlaca;
    }
    
    public void setMmsTipoPlaca(String mmsTipoPlaca) {
        this.mmsTipoPlaca = mmsTipoPlaca;
    }




}


