package bean;
// Generated 13/11/2023 18:58:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MmsProduto generated by hbm2java
 */
@Entity
@Table(name="mms_produto"
    ,catalog="db_mathias_fleitas"
)
public class MmsProduto  implements java.io.Serializable {


     private int mmsIdproduto;
     private String mmsNome;
     private String mmsDescricao;
     private Double mmsPreco;
     private String mmsConsumo;
     private String mmsMemoria;
     private String mmsDimensao;
     private int mmsPeso;
     private String mmsMarca;
     private String mmsGarantia;
     private String mmsModelo;

    public MmsProduto() {
    }

    public MmsProduto(int mmsIdproduto, String mmsNome, String mmsDescricao, Double mmsPreco, String mmsConsumo, String mmsMemoria, String mmsDimensao, int mmsPeso, String mmsMarca, String mmsGarantia, String mmsModelo) {
       this.mmsIdproduto = mmsIdproduto;
       this.mmsNome = mmsNome;
       this.mmsDescricao = mmsDescricao;
       this.mmsPreco = mmsPreco;
       this.mmsConsumo = mmsConsumo;
       this.mmsMemoria = mmsMemoria;
       this.mmsDimensao = mmsDimensao;
       this.mmsPeso = mmsPeso;
       this.mmsMarca = mmsMarca;
       this.mmsGarantia = mmsGarantia;
       this.mmsModelo = mmsModelo;
    }
   
     @Id 

    
    @Column(name="mms_idproduto", unique=true, nullable=false)
    public int getMmsIdproduto() {
        return this.mmsIdproduto;
    }
    
    public void setMmsIdproduto(int mmsIdproduto) {
        this.mmsIdproduto = mmsIdproduto;
    }

    
    @Column(name="mms_nome", nullable=false, length=45)
    public String getMmsNome() {
        return this.mmsNome;
    }
    
    public void setMmsNome(String mmsNome) {
        this.mmsNome = mmsNome;
    }

    
    @Column(name="mms_descricao", nullable=false)
    public String getMmsDescricao() {
        return this.mmsDescricao;
    }
    
    public void setMmsDescricao(String mmsDescricao) {
        this.mmsDescricao = mmsDescricao;
    }

    
    @Column(name="mms_preco", nullable=false, precision=8)
    public Double getMmsPreco() {
        return this.mmsPreco;
    }
    
    public void setMmsPreco(Double mmsPreco) {
        this.mmsPreco = mmsPreco;
    }

    
    @Column(name="mms_consumo", nullable=false, length=15)
    public String getMmsConsumo() {
        return this.mmsConsumo;
    }
    
    public void setMmsConsumo(String mmsConsumo) {
        this.mmsConsumo = mmsConsumo;
    }

    
    @Column(name="mms_memoria", nullable=false, length=20)
    public String getMmsMemoria() {
        return this.mmsMemoria;
    }
    
    public void setMmsMemoria(String mmsMemoria) {
        this.mmsMemoria = mmsMemoria;
    }

    
    @Column(name="mms_dimensao", nullable=false, length=60)
    public String getMmsDimensao() {
        return this.mmsDimensao;
    }
    
    public void setMmsDimensao(String mmsDimensao) {
        this.mmsDimensao = mmsDimensao;
    }

    
    @Column(name="mms_peso", nullable=false)
    public int getMmsPeso() {
        return this.mmsPeso;
    }
    
    public void setMmsPeso(int mmsPeso) {
        this.mmsPeso = mmsPeso;
    }

    
    @Column(name="mms_marca", nullable=false, length=45)
    public String getMmsMarca() {
        return this.mmsMarca;
    }
    
    public void setMmsMarca(String mmsMarca) {
        this.mmsMarca = mmsMarca;
    }

    
    @Column(name="mms_garantia", nullable=false, length=20)
    public String getMmsGarantia() {
        return this.mmsGarantia;
    }
    
    public void setMmsGarantia(String mmsGarantia) {
        this.mmsGarantia = mmsGarantia;
    }

    
    @Column(name="mms_modelo", nullable=false, length=30)
    public String getMmsModelo() {
        return this.mmsModelo;
    }
    
    public void setMmsModelo(String mmsModelo) {
        this.mmsModelo = mmsModelo;
    }




}


