package bean;
// Generated 13/11/2023 18:58:12 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MmsVendas generated by hbm2java
 */
@Entity
@Table(name="mms_vendas"
    ,catalog="db_mathias_fleitas"
)
public class MmsVendas  implements java.io.Serializable {


     private int mmsIdVendas;
     private Integer mmsCliente;
     private Date mmsDataVenda;
     private String mmsValor;
     private int mmsVendedores;

    public MmsVendas() {
    }

	
    public MmsVendas(int mmsIdVendas, Date mmsDataVenda, String mmsValor, int mmsVendedores) {
        this.mmsIdVendas = mmsIdVendas;
        this.mmsDataVenda = mmsDataVenda;
        this.mmsValor = mmsValor;
        this.mmsVendedores = mmsVendedores;
    }
    public MmsVendas(int mmsIdVendas, Integer mmsCliente, Date mmsDataVenda, String mmsValor, int mmsVendedores) {
       this.mmsIdVendas = mmsIdVendas;
       this.mmsCliente = mmsCliente;
       this.mmsDataVenda = mmsDataVenda;
       this.mmsValor = mmsValor;
       this.mmsVendedores = mmsVendedores;
    }
   
     @Id 

    
    @Column(name="mms_idVendas", unique=true, nullable=false)
    public int getMmsIdVendas() {
        return this.mmsIdVendas;
    }
    
    public void setMmsIdVendas(int mmsIdVendas) {
        this.mmsIdVendas = mmsIdVendas;
    }

    
    @Column(name="mms_cliente")
    public Integer getMmsCliente() {
        return this.mmsCliente;
    }
    
    public void setMmsCliente(Integer mmsCliente) {
        this.mmsCliente = mmsCliente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mms_dataVenda", nullable=false, length=10)
    public Date getMmsDataVenda() {
        return this.mmsDataVenda;
    }
    
    public void setMmsDataVenda(Date mmsDataVenda) {
        this.mmsDataVenda = mmsDataVenda;
    }

    
    @Column(name="mms_valor", nullable=false, length=45)
    public String getMmsValor() {
        return this.mmsValor;
    }
    
    public void setMmsValor(String mmsValor) {
        this.mmsValor = mmsValor;
    }

    
    @Column(name="mms_vendedores", nullable=false)
    public int getMmsVendedores() {
        return this.mmsVendedores;
    }
    
    public void setMmsVendedores(int mmsVendedores) {
        this.mmsVendedores = mmsVendedores;
    }




}


