package bean;
// Generated 22/09/2023 15:20:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MmsVendasProduto generated by hbm2java
 */
@Entity
@Table(name="mms_vendas_produto"
    ,catalog="db_mathias_fleitas"
)
public class MmsVendasProduto  implements java.io.Serializable {


     private int mmsIdvendasProduto;
     private Integer mmsVenda;
     private Integer mmsProduto;
     private String mmsQuantidade;
     private BigDecimal mmsValorUnitario;

    public MmsVendasProduto() {
    }

	
    public MmsVendasProduto(int mmsIdvendasProduto, String mmsQuantidade, BigDecimal mmsValorUnitario) {
        this.mmsIdvendasProduto = mmsIdvendasProduto;
        this.mmsQuantidade = mmsQuantidade;
        this.mmsValorUnitario = mmsValorUnitario;
    }
    public MmsVendasProduto(int mmsIdvendasProduto, Integer mmsVenda, Integer mmsProduto, String mmsQuantidade, BigDecimal mmsValorUnitario) {
       this.mmsIdvendasProduto = mmsIdvendasProduto;
       this.mmsVenda = mmsVenda;
       this.mmsProduto = mmsProduto;
       this.mmsQuantidade = mmsQuantidade;
       this.mmsValorUnitario = mmsValorUnitario;
    }
   
     @Id 

    
    @Column(name="mms_idvendas_produto", unique=true, nullable=false)
    public int getMmsIdvendasProduto() {
        return this.mmsIdvendasProduto;
    }
    
    public void setMmsIdvendasProduto(int mmsIdvendasProduto) {
        this.mmsIdvendasProduto = mmsIdvendasProduto;
    }

    
    @Column(name="mms_venda")
    public Integer getMmsVenda() {
        return this.mmsVenda;
    }
    
    public void setMmsVenda(Integer mmsVenda) {
        this.mmsVenda = mmsVenda;
    }

    
    @Column(name="mms_produto")
    public Integer getMmsProduto() {
        return this.mmsProduto;
    }
    
    public void setMmsProduto(Integer mmsProduto) {
        this.mmsProduto = mmsProduto;
    }

    
    @Column(name="mms_quantidade", nullable=false, length=45)
    public String getMmsQuantidade() {
        return this.mmsQuantidade;
    }
    
    public void setMmsQuantidade(String mmsQuantidade) {
        this.mmsQuantidade = mmsQuantidade;
    }

    
    @Column(name="mms_valorUnitario", nullable=false, precision=8)
    public BigDecimal getMmsValorUnitario() {
        return this.mmsValorUnitario;
    }
    
    public void setMmsValorUnitario(BigDecimal mmsValorUnitario) {
        this.mmsValorUnitario = mmsValorUnitario;
    }




}


